server:
  port: 8080
  logging:
    level:
      org.springframework.jdbc.datasource.init.ScriptUtils: debug

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    jpa:
      hibernate:
        ddl-auto: "none"

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8085

---
spring:
  config:
    activate:
      on-profile: qa
server:
  port: 8086

