server:
  port: 8080
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              scriptUtils: debug
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    password:
    driverClassName: org.h2.Driver
